name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          cmake --preset linux-release "-DAPP_VERSION_OVERRIDE=${{ github.ref_name }}"
          cmake --build --preset linux-release -j

      - name: rename
        run: |
          cp build-linux/opicochat opicochat-linux-x64
          cp build-linux/opicochat_server opicochat_server-linux-x64

      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: |
            opicochat-linux-x64
            opicochat_server-linux-x64

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          cmake --preset windows-msvc-release "-DAPP_VERSION_OVERRIDE=${{ github.ref_name }}"
          cmake --build --preset windows-msvc-release -j

      - name: rename
        run: |
          cp build-windows/Release/opicochat.exe opicochat-windows-x64.exe
          cp build-windows/Release/opicochat_server.exe opicochat_server-windows-x64.exe

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            opicochat-windows-x64.exe
            opicochat_server-windows-x64.exe

  build-macos-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release "-DAPP_VERSION_OVERRIDE=${{ github.ref_name }}"
          cmake --build build -j

      - name: rename
        run: |
          cp build/opicochat opicochat-macos-arm64
          cp build/opicochat_server opicochat_server-macos-arm64

      - uses: actions/upload-artifact@v4
        with:
          name: macos-arm
          path: |
            opicochat-macos-arm64
            opicochat_server-macos-arm64

  release:
    needs: [build-linux, build-windows, build-macos-arm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            opicochat-linux-x64
            opicochat_server-linux-x64
            opicochat-windows-x64.exe
            opicochat_server-windows-x64.exe
            opicochat-macos-arm64
            opicochat_server-macos-arm64
          generate_release_notes: true
